### ISSUE TITLE
ERROR while executing index2d command - df['node'] = node 

### ISSUE THREAD

**Issue by AbdelghaniTamort** [Yarroudh/Optim3D#8]
[issue.log](https://github.com/Yarroudh/Optim3D/files/11463176/issue.log)

**Comment by Yarroudh** [comment]
@AbdelghaniTamort thanks for sharing this issue, can you share with you environment as YAML file?
You can run `conda env export --name optimenv --file optimenv.yml`

**Comment by baal-lgln** [comment]
Hi, I'm using the docker image (yarroudh/optim3d) and get a similar error message when I try to run `optim3d index2d /home/user/data/wippolder.gpkg`:
```
/opt/mambaforge/lib/python3.10/site-packages/optim3d/main.py:360: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  quadTree = QuadTree(Bounds(float(bounds.minx), float(bounds.miny), float(width), float(height)), max_objects=max)
/opt/mambaforge/lib/python3.10/site-packages/geopandas/io/file.py:545: UserWarning: You are attempting to write an empty DataFrame to file. For some drivers, this operation may fail.
  _to_file_fiona(df, filename, driver, schema, crs, mode, **kwargs)
Traceback (most recent call last):
  File "/opt/mambaforge/bin/optim3d", line 8, in <module>
    sys.exit(cli())
  File "/opt/mambaforge/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/opt/mambaforge/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/opt/mambaforge/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/mambaforge/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/mambaforge/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/opt/mambaforge/lib/python3.10/site-packages/optim3d/main.py", line 378, in index2d
    df['node'] = node
  File "/opt/mambaforge/lib/python3.10/site-packages/geopandas/geodataframe.py", line 1443, in __setitem__
    super().__setitem__(key, value)
  File "/opt/mambaforge/lib/python3.10/site-packages/pandas/core/frame.py", line 3959, in __setitem__
    self._set_item(key, value)
  File "/opt/mambaforge/lib/python3.10/site-packages/pandas/core/frame.py", line 4152, in _set_item
    value = self._sanitize_column(value)
  File "/opt/mambaforge/lib/python3.10/site-packages/pandas/core/frame.py", line 4878, in _sanitize_column
    com.require_length_match(value, self.index)
  File "/opt/mambaforge/lib/python3.10/site-packages/pandas/core/common.py", line 576, in require_length_match
    raise ValueError(
ValueError: Length of values (0) does not match length of index (60)
```

Testdata is obtained from here: https://data.3dgi.xyz/roofer-test-data/
